Backup data from h2 (#32)

diff --git a/src/h2/service b/src/h2/service
--- a/src/h2/service
+++ b/src/h2/service
@@ -29,7 +29,32 @@ case "$1" in
     docker rm --force $DOCKER_SERVICE_NAME
     ;;
 
+  backup)
+    backup_file=$2
+    if [ -z "$backup_file" ]; then
+      echo "Missing backup file path" 1>&2
+      exit 1
+    fi
+
+    echo "Building image $DOCKER_IMAGE_NAME"
+    docker build -t $DOCKER_IMAGE_NAME $ROOT/src/h2
+
+    echo "Backing up data from container $DOCKER_IMAGE_NAME"
+    docker run \
+      -it --rm \
+      --volume $ROOT/src/h2/tiefvision.mv.db:/root/tiefvision.mv.db \
+      --entrypoint java \
+      $DOCKER_IMAGE_NAME \
+        -cp /opt/h2.jar org.h2.tools.Shell \
+        -url jdbc:h2:~/tiefvision \
+        -user sa \
+        -sql SCRIPT \
+          | sed 1d \
+          | sed \$d \
+          > $backup_file
+    ;;
+
   *)
-    echo $"Usage: $0 {start|stop}"
+    echo $"Usage: $0 {start|stop|backup FILE}"
     exit 1
 esac
